project:
  type: book
  output-dir: _book

book:
  title: "Text Analysis in R for Media and Communication"
  author: "Your Name"
  date: today
  date-format: "YYYY"
  repo-url: https://github.com/vanatteveldt/tarmac
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-funwithr.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  live-html:
    theme:
      - flatly
      - style.scss
    fontsize: 0.9em
    toc: true
    number-sections: true
    number-depth: 2

engine: knitr

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
